### ISSUE TITLE
Unable to install from GitHub

### ISSUE THREAD

**Issue by ajkristof18** [lucidif/HiCeekR#3]
Hi, 

I have followed the instructions in the manual for installation from Github, and after quite a few attempts am still unable to install HiCeekR from this repository. Attached below is a Word doc with the message from R - hopefully this will be useful in assessing the problem. 

Thanks,
-Andrew Kristof
[HiCeekR Install Error.docx](https://github.com/lucidif/HiCeekR/files/4087256/HiCeekR.Install.Error.docx)

**Comment by rw383** [comment]
I also have the same problem and error messages about unused arguments. Please advise ASAP.

**Comment by drighelli** [comment]
Hi thanks for reporting this issue, @ajkristof18  and @rw383 could you please report the operative system details (also the R version)? Type and version.
We'll check on it.

**Comment by junmeiW** [comment]
I  also met the same problem when runing the code below:
`install_github("lucidif/HiCeekR", repos=BiocManager::repositories())`

and I got the error 

```
HiCseg_linkR.c:11:10: fatal error: gsl/gsl_matrix.h: No such file or directory
 #include <gsl/gsl_matrix.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:168: HiCseg_linkR.o] Error 1
ERROR: compilation failed for package ‘HiCseg’
* removing ‘/home/wangjm/R/x86_64-pc-linux-gnu-library/3.6/HiCseg’
Error: Failed to install 'HiCeekR' from GitHub:
  (converted from warning) installation of package 'HiCseg' had non-zero exit status
```
My system details is shown as this 
```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.3                         
year           2020                        
month          02                          
day            29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
```

**Comment by drighelli** [comment]
Hi @junmeiW,

this is because you're missing the gsl libraries on your machine.

If you're using an ubuntu-like distribution you need to install them via `sudo apt-get install libgsl-dev`

Additional installation information can be found at 

https://gist.github.com/TysonRayJones/af7bedcdb8dc59868c7966232b4da903#installation

Hope this helps.
Dario

**Comment by junmeiW** [comment]
@drighelli Thank you for your reply,  let me have a try for it.

Thanks again!

**Comment by junmeiW** [comment]
@drighelli Hi, I've install the gsl libraried accoring to your suhhestion,  and I rerun the code:
```
install_github("lucidif/HiCeekR", repos=BiocManager::repositories())
``` 
got another error:
```
 the dependency 'chromoR' id not available for  HiCeekR
```
then i  install the package by 
```
BiocManager::install("chromoR")
```
but  I got
``` package 'chromoR' is not available (for R version 3.6.3) ```
and I found the package address [https://cran.r-project.org/web/packages/chromoR/index.html](url) did not provide suitable package.

So what can i do for this problem!
Tahnk you !

**Comment by lucidif** [comment]
hi @junmeiW ,
the chromoR package is no longer supported, but I should have fixed the problem.
Best regards,
Lucio

**Comment by drighelli** [comment]
Maybe you can close this issue now...
